apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devops-base
data:
  APP_ENV: "development"
  APP_PORT: "5000"
  LOG_PATH: "/var/log/app/access.log"
  POSTGRES_USER: "admin"
  POSTGRES_DB: "myapp"