#!/bin/bash

# Script with instructions for obtaining real Let's Encrypt certificates
# This script shows the certbot commands needed for SSL certificate management

echo "=========================================="
echo "Let's Encrypt Certificate Setup Guide"
echo "=========================================="
echo ""
echo "This script provides the certbot commands needed for:"
echo "1. Initial certificate obtainment"
echo "2. Certificate renewal"
echo "3. Dry-run testing"
echo ""
echo "=========================================="
echo "PREREQUISITES"
echo "=========================================="
echo ""
echo "1. Install certbot:"
echo "   sudo apt update"
echo "   sudo apt install certbot python3-certbot-nginx"
echo ""
echo "2. Ensure your domain is pointed to this server"
echo "   and port 80 (HTTP) is accessible from the internet."
echo ""
echo "=========================================="
echo "INITIAL CERTIFICATE OBTAINMENT"
echo "=========================================="
echo ""
echo "For a standalone server (without nginx):"
echo "sudo certbot certonly --standalone -d yourdomain.com -d www.yourdomain.com"
echo ""
echo "For nginx web server:"
echo "sudo certbot --nginx -d yourdomain.com -d www.yourdomain.com"
echo ""
echo "For Apache web server:"
echo "sudo certbot --apache -d yourdomain.com -d www.yourdomain.com"
echo ""
echo "Replace 'yourdomain.com' with your actual domain name."
echo ""
echo "=========================================="
echo "CERTIFICATE RENEWAL"
echo "=========================================="
echo ""
echo "Manual renewal:"
echo "sudo certbot renew"
echo ""
echo "Renewal with dry-run (test renewal without actually renewing):"
echo "sudo certbot renew --dry-run"
echo ""
echo "Auto-renewal is typically set up automatically during installation."
echo "You can check the renewal timer with:"
echo "sudo systemctl status certbot.timer"
echo ""
echo "=========================================="
echo "CERTIFICATE LOCATION"
echo "=========================================="
echo ""
echo "After obtaining certificates, they will be located at:"
echo "Certificate: /etc/letsencrypt/live/yourdomain.com/fullchain.pem"
echo "Private Key: /etc/letsencrypt/live/yourdomain.com/privkey.pem"
echo "Chain: /etc/letsencrypt/live/yourdomain.com/chain.pem"
echo ""
echo "=========================================="
echo "REVOKING CERTIFICATES (if needed)"
echo "=========================================="
echo ""
echo "To revoke a certificate:"
echo "sudo certbot revoke --cert-path /etc/letsencrypt/live/yourdomain.com/cert.pem"
echo ""
echo "To delete a certificate:"
echo "sudo certbot delete --cert-name yourdomain.com"
echo ""
echo "=========================================="
echo "IMPORTANT NOTES"
echo "=========================================="
echo ""
echo "- Let's Encrypt certificates are valid for 90 days"
echo "- Auto-renewal should be configured to run before expiration"
echo "- Ensure your firewall allows HTTP (port 80) for ACME challenges"
echo "- Use --dry-run to test renewal before actual expiration"
echo ""
echo "=========================================="
echo "For more information, visit: https://letsencrypt.org/docs/"
echo "=========================================="